# Generated by Django 6.0.6 on 2026-07-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='card_back_color',
            field=models.CharField(default='#143d2f', max_length=9),
        ),
        migrations.AddField(
            model_name='team',
            name='felt_color',
            field=models.CharField(default='#10b981', max_length=9),
        ),
    ]
