# Generated by Django 6.0.6 on 2026-07-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_card_back_color_team_felt_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='team',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='team',
            name='subscription_current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='subscription_status',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
