# Generated by Django 6.0.6 on 2026-07-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_stripe_customer_id_team_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='subscription_current_period_end',
        ),
        migrations.RemoveField(
            model_name='team',
            name='subscription_status',
        ),
    ]
