# Generated by Django 6.0.6 on 2026-07-19 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_cardback_cardbacktranslation'),
        ('teams', '0005_team_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='card_back',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='decks.cardback'),
        ),
    ]
