# Generated by Django 6.0.6 on 2026-07-19 14:56

from django.db import migrations, models


def carry_pick_into_m2m(apps, schema_editor):
    """A team's single pick becomes its first enabled deck.

    Ordered before RemoveField so the FK is still readable; without this the
    existing choice would be silently dropped.
    """
    Team = apps.get_model("teams", "Team")
    for team in Team.objects.filter(deck__isnull=False).iterator():
        team.decks.add(team.deck_id)


def back_to_single_pick(apps, schema_editor):
    Team = apps.get_model("teams", "Team")
    for team in Team.objects.iterator():
        first = team.decks.order_by("pk").first()
        if first is not None:
            team.deck_id = first.pk
            team.save(update_fields=["deck"])


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0004_alter_deck_team'),
        ('teams', '0006_team_card_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='decks',
            field=models.ManyToManyField(blank=True, related_name='teams_enabled', to='decks.deck'),
        ),
        migrations.RunPython(carry_pick_into_m2m, back_to_single_pick),
        migrations.RemoveField(
            model_name='team',
            name='deck',
        ),
    ]
