# Generated by Django 6.0.6 on 2026-07-19 16:53

from django.db import migrations, models


def admin_to_manager(apps, schema_editor):
    """Carry existing rows over. Without this every current admin — and every
    pending invitation sent as admin — would keep the value "admin", which is no
    longer a valid role: they would silently lose their rights.
    """
    for model in ("TeamMembership", "Invitation"):
        apps.get_model("teams", model).objects.filter(role="admin").update(role="manager")


def manager_to_admin(apps, schema_editor):
    for model in ("TeamMembership", "Invitation"):
        apps.get_model("teams", model).objects.filter(role="manager").update(role="admin")


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_remove_team_deck_team_decks'),
    ]

    operations = [
        migrations.RunPython(admin_to_manager, manager_to_admin),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('member', 'Member')], default='member', max_length=12),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('member', 'Member')], default='member', max_length=12),
        ),
    ]
