# Generated by Django 6.0.6 on 2026-07-19 17:05

import django.db.models.deletion
from django.db import migrations, models


def keep_existing_card_back_choice(apps, schema_editor):
    """A team that already picked a card back meant to use it.

    The new discriminator defaults to "color", so without this their chosen back
    would stop being applied the moment this migration runs.
    """
    Team = apps.get_model("teams", "Team")
    Team.objects.filter(card_back__isnull=False).update(card_back_style="image")


def noop(apps, schema_editor):
    """Nothing to undo: the column itself is dropped on reverse."""


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0008_felt'),
        ('teams', '0008_alter_invitation_role_alter_teammembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='card_back_style',
            field=models.CharField(choices=[('color', 'Flat colour'), ('image', 'Image from the catalogue')], default='color', max_length=8),
        ),
        migrations.AddField(
            model_name='team',
            name='felt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='decks.felt'),
        ),
        migrations.AddField(
            model_name='team',
            name='felt_style',
            field=models.CharField(choices=[('color', 'Flat colour'), ('image', 'Image from the catalogue')], default='color', max_length=8),
        ),
        migrations.RunPython(keep_existing_card_back_choice, noop),
    ]
