# Generated by Django 6.0.7 on 2026-08-10 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0014_background'),
        ('teams', '0010_team_result_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='decks.background'),
        ),
        migrations.AddField(
            model_name='team',
            name='background_color',
            field=models.CharField(default='#0f172a', max_length=9),
        ),
        migrations.AddField(
            model_name='team',
            name='background_style',
            field=models.CharField(choices=[('theme', 'Follow the light/dark theme'), ('color', 'Flat colour'), ('image', 'Image from the catalogue')], default='theme', max_length=8),
        ),
    ]
