# Generated by Django 6.0.6 on 2026-07-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_participants',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
