# Generated by Django 6.0.6 on 2026-07-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='timer_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='timer_seconds',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='votesession',
            name='vote_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
