# Generated by Django 6.0.6 on 2026-07-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_timer_enabled_room_timer_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='deck_snapshots',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='votesession',
            name='deck_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
