# Generated by Django 6.0.6 on 2026-07-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_deck_snapshots_votesession_deck_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='votesession',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
