# Generated by Django 6.0.7 on 2026-08-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_votesession_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='max_participants',
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
