# Generated by Django 6.0.6 on 2026-07-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_display_name_magiclinktoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bypass_granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bypass_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_bypass',
            field=models.BooleanField(default=False),
        ),
    ]
