# Generated by Django 6.0.6 on 2026-07-18 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bypassgrantlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bypassgrantlog',
            name='target_label',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='bypassgrantlog',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bypass_grants_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
