# Generated by Django 6.0.6 on 2026-07-08 15:10

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_standard', models.BooleanField(default=True)),
                ('card_back_image', models.ImageField(upload_to='decks/backs/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='VoteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('resolution_strategy', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=32)),
                ('slug', models.SlugField()),
                ('order', models.PositiveSmallIntegerField()),
                ('background_image', models.ImageField(upload_to='decks/cards/')),
                ('is_active', models.BooleanField(default=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='decks.deck')),
            ],
            options={
                'ordering': ('deck', 'order'),
            },
        ),
        migrations.CreateModel(
            name='DeckTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=120)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='decks.deck')),
            ],
            options={
                'verbose_name': 'deck Translation',
                'db_table': 'decks_deck_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TextLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('pos_x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pos_y', models.DecimalField(decimal_places=2, max_digits=5)),
                ('font_family', models.CharField(default='Inter', max_length=80)),
                ('font_size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('font_weight', models.PositiveSmallIntegerField(default=400)),
                ('color', models.CharField(default='#ffffff', max_length=9)),
                ('align', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=6)),
                ('content_kind', models.CharField(choices=[('static', 'Static (one value, all languages)'), ('i18n', 'Translated (per-language)')], default='i18n', max_length=6)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='decks.card')),
            ],
            options={
                'ordering': ('card', 'order'),
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TextLayerTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('content', models.CharField(max_length=200)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='decks.textlayer')),
            ],
            options={
                'verbose_name': 'text layer Translation',
                'db_table': 'decks_textlayer_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='deck',
            name='vote_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decks', to='decks.votetype'),
        ),
        migrations.CreateModel(
            name='VoteTypeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=120)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='decks.votetype')),
            ],
            options={
                'verbose_name': 'vote type Translation',
                'db_table': 'decks_votetype_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(fields=('deck', 'value'), name='uniq_card_deck_value'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(fields=('deck', 'order'), name='uniq_card_deck_order'),
        ),
        migrations.AddConstraint(
            model_name='decktranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='decks_deck_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='textlayertranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='decks_textlayer_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='votetypetranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='decks_votetype_translation_uniq_lang'),
        ),
    ]
