# Generated by Django 6.0.6 on 2026-07-19 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_cardback_cardbacktranslation'),
        ('teams', '0006_team_card_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_decks', to='teams.team'),
        ),
    ]
