# Generated by Django 6.0.6 on 2026-07-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0004_alter_deck_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardback',
            name='free_tier',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='free_tier',
            field=models.BooleanField(default=True),
        ),
    ]
