# Generated by Django 6.0.6 on 2026-07-19 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0007_rename_legacy_name_cardback_name'),
        ('teams', '0008_alter_invitation_role_alter_teammembership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Felt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_standard', models.BooleanField(default=True)),
                ('free_tier', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('image', models.ImageField(upload_to='decks/felts/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='felts', to='teams.team')),
            ],
        ),
    ]
