# Generated by Django 6.0.6 on 2026-07-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0008_felt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardback',
            name='team',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='team',
        ),
        migrations.RemoveField(
            model_name='felt',
            name='team',
        ),
    ]
