# Generated by Django 6.0.7 on 2026-08-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0010_cardback_uploaded_by_felt_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textlayer',
            name='content_kind',
            field=models.CharField(choices=[('static', 'Static (one value, all languages)'), ('i18n', 'Translated (per-language)'), ('icon', "Icon key (resolved by the client's icon registry)")], default='i18n', max_length=6),
        ),
    ]
