# Generated by Django 6.0.7 on 2026-08-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0011_textlayer_icon_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='textlayer',
            name='image',
            field=models.ImageField(blank=True, upload_to='decks/icons/'),
        ),
        migrations.AlterField(
            model_name='textlayer',
            name='content_kind',
            field=models.CharField(choices=[('static', 'Static (one value, all languages)'), ('i18n', 'Translated (per-language)'), ('icon', "Icon (draws the layer's uploaded image)")], default='i18n', max_length=6),
        ),
        migrations.AlterField(
            model_name='textlayertranslation',
            name='content',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
