# Generated by Django 6.0.6 on 2026-07-09 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='BoardRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('as_is_level', models.CharField(blank=True, max_length=32, null=True)),
                ('to_be_level', models.CharField(blank=True, max_length=32, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='boards.board')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
